# Tema 1

__1.1 Să se cifreze textul reprezentat de numele dumneavoastră de familie, prin algoritmul Cezar. Cheia utilizata este numărul de litere din numele de familie. Verificaţi rezultatul prin descifrare.__

Nume: __CIOBANU__

Cheie: __7__

Operatie: __ROT(7)__

Alphabet | ABCDEFGHIJKLMNOPQRSTUVXYZ
     ---|---
Cipher  | HIJKLMNOPQRSTUVWXZABCDEFG
Text criptat = JPVIHUB

In [25]:
nume = "ciobanu"
key = 7
def enc(str):
    encrypted = []
    for litera in str:
        encrypted.append(chr((ord(litera) - ord('a') + key) % 26 + ord('a')))
    result = "".join(encrypted)
    return result

def dec(str):
    decrypted = []
    for litera in str:
        decrypted.append(chr((ord(litera) - ord('a') - key) % 26 + ord('a')))
    result = "".join(decrypted)
    return result

if __name__== "__main__":
    print(enc(nume))
    print(dec(enc(nume)))

jpvihub
ciobanu


__1.2 Să se cifreze textul reprezentat de numele dumneavoastră de familie, prin metoda substituţiei. Cheia utilizată este prenumele dumneavoastra. Verificaţi rezultatul prin descifrare.__

Nume: __CIOBANU__

Cheie: __COSMIN__

Nume Criptat: __sdkocjt__

Alphabet | ABCDEFGHIJKLMNOPQRSTUVWXYZ
--- | ---
Cipher   | COSMINABDEFGHJKLPQRSTUVXYZ

In [31]:
import string
nume = "ciobanu"
key = "cosmin"

a = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"]
b = ["c","o","s","m","i","n","a","b","d","e","f","g","h","j","k","l","p","q","r","s","t","u","v","x","y","z"]

dict_list = dict(zip(a, b))
res = []
for item in nume:
        res.append(dict_list[item])
print("".join(res))

sdkocjt


__1.3 Să se cifreze textul reprezentat de numele dumneavoastra de familie, prin metoda __Playfair__. Cheia utilizată este prenumele dumneavoastră. Verificaţi rezultatul prin descifrare.__

Nume:  CIOBANU

Cheie: COSMIN

C | O | S | M | I/J
--|---|---|---|---
__N__ | A | B | D | E
F | G | H | K | L
P | Q | R | T | U
V | W | X | Y | Z

Reguli pentru criptare:

a) Daca ambele litere se afla pe acelasi rand , literele trebuie inlocuite cu litera din dreapta fiecareia. In cazul in care una din litere este la capat se revine la inceputul aceluiasi rand si litera din capat se inlocuieste cu cea de la inceputul randului.

b) Daca ambele litere se afla pe aceiasi coloana, literele trebuie inlocuite cu literele aflate sub fiecare. In cazul in care una din litere este la baza coloanei se revine la inceputului coloanei si se inlocuieste litera de la inceputul coloanei cu cea de la baza coloanei.

c) Daca niciuna din litere nu se afla pe aceiasi linie sau coloana, se delimiteaza un patrat cu elementele diagonale constituite de literele date , se noteaza literele aflate la diagonala opusa.


Cuvantul care urmeaza sa fie criptat se imparte in grupuri de cate doua litere, in cazul in care numarul literelor din cuvant nu este multiplu de 2 se adauga litera X la sfarsit pentru a forma ultima pereche.

Text de criptat: | CI | OB| AN | UX
--- | --- | --- | ----
Regula aplicata:| a) | c) | a) | a) 
Criptare | OC | SA | BA | RZ

Reguli pentru decriptare:

i) Daca ambele litere se afla pe acelasi rand, se inlocuiesc cu literele corespunzatoare din stanga fiecarei litere initiale. Daca litera se afla la inceputlui randului atunci se inlocuieste cu litera aflata la capatul aceluiasi rand.

ii) Daca ambele litere se afla pe aceiasi coloana, se inlocuiesc cu litere corespunzatoare aflate deasupra fiecare litere date. Daca litera este la inceputul coloanei, se va inlocui cu litera de la baza coloanei.

iii) Daca niciuna din litere nu se afla pe acelasi rand sau coloana, se delimiteaza un patrat cu elementele diagonale constituite de literele date, se noteaza literele aflate la diagonala opusa.


C | O | S | M | I/J
--|---|---|---|---
__N__ | A | B | D | E
F | G | H | K | L
P | Q | R | T | U 
V | W | X | Y | Z

Criptare | OC | SA | BA | RZ
--- | --- | --- | ----
Regula aplicata | i) | iii) | i) | iii)
Text | CI | OB | AN | UX

In [13]:
import string
from itertools import product
text =['ci','ob','an','ux']
text2 = ['oc','sa','ba','rz']

key = ['c','o','s','m','i','n']t
alphabet =  list(string.ascii_lowercase)
alphabet.remove('j')
for chr in key:
        alphabet.remove(chr)

alphabet = key+alphabet
matrix = [alphabet[i:i+5] for i in range(0,len(alphabet),5)]

#[['c' 'o' 's' 'm' 'i']
# ['n' 'a' 'b' 'd' 'e']
# ['f' 'g' 'h' 'k' 'l']
# ['p' 'q' 'r' 't' 'u']
# ['v' 'w' 'x' 'y' 'z']]

def pf_encrypt(di,PF):
    for i in range(5):
        for j in range(5):
            if PF[i][j]==di[0]:
                i0=i
                j0=j
            if PF[i][j]==di[1]:
                i1=i
                j1=j
    if (i0!=i1) & (j0!=j1):
        return PF[i0][j1]+PF[i1][j0]
    if (i0==i1) & (j0!=j1):
        return PF[i0][(j0+1)%5]+PF[i1][(j1+1)%5]
    if (i0!=i1) & (j0==j1):
        return PF[(i0+1)%5][j0]+PF[(i1+1)%5][j1]

def pf_decrypt(di,PF):
        for i in range(5):
                for j in range(5):
                        if PF[i][j] == di[0]:
                                i0 = i
                                j0 = j
                        if PF[i][j] == di[1]:
                                i1 = i
                                j1 = j
        if i0!=i1 and j0!=j1:
                return PF[i0][j1]+PF[i1][j0]
        if (i0==i1) & (j0!=j1):
                return PF[i0][(j0-1)%5]+PF[i1][(j1-1)%5]
        if (i0!=i1) & (j0==j1):
                return PF[(i0-1)%5][j0]+PF[(i1-1)%5][j1]

for item in text:
        print('Encrypted',pf_encrypt(item,matrix))
for item in text2:
        print('Decrypt',pf_decrypt(item,matrix))

Encrypted oc
Encrypted sa
Encrypted ba
Encrypted rz
Decrypt ci
Decrypt ob
Decrypt an
Decrypt ux


__1.4 Să se cifreze textul reprezentat de numele dumneavoastră de familie, cu ajutorul algoritmului Hill 2 x 2. Cheia utilizata este reprezentată de o matrice aleasa de dumneavoastra. Verificaţi rezultatul prin descifrare.__

Criptarea:

 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |10 |11 | 12|13 |14 |15 |16 |17 |18 |19 |20 |21 |22 |23 |24 | 25
---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
 A | B | C | D | E | F | G | H | I | J | K | L | M | N | O | P | Q | R | S | T | U | V | W | X | Y | Z

Se alege o matrice 2x2 inversabila modulo 26 cu elementele aleatoare.


$$\begin{equation}
\mathbf{Key} =
\begin{pmatrix}
11 & 1 \\
3 & 6 \\
\end{pmatrix}
\end{equation}$$

Text de cifrat: __CI OB AN UX__ 

Textul ce urmeaza a fi cifrat se imparte in grupuri a cate doua elemente care se vor inlocui cu valorile corespunzatoare din tabelul de mai sus. In cazul in care numarul de caractere nu este multiplu de 2 se adauga litera X ca padding.

$$\begin{pmatrix} C \\ I \end{pmatrix} = \begin{pmatrix} 2 \\ 8 \end{pmatrix},  
\begin{pmatrix} O \\ B \end{pmatrix} = \begin{pmatrix} 14 \\ 1 \end{pmatrix},  
\begin{pmatrix} A \\ N \end{pmatrix} = \begin{pmatrix} 0 \\ 13 \end{pmatrix}, 
\begin{pmatrix} U \\ X\end{pmatrix}  = \begin{pmatrix} 20 \\ 23 \end{pmatrix}$$

In continuare se inmultesc matricile rezultate formate din 2 elemente cu matricea Key modulo 26.

$$\begin{equation}
\begin{pmatrix}
11 & 1 \\
3 & 6 \\
\end{pmatrix} \times \begin{pmatrix} 2 \\ 8 \end{pmatrix} =  \begin{pmatrix} 30 \\ 54 \end{pmatrix} \mod 26 = \begin{pmatrix} 4 \\ 2 \end{pmatrix} = \begin{pmatrix} E \\ C \end{pmatrix} 
\end{equation}$$

$$\begin{equation}
\begin{pmatrix}
11 & 1 \\
3 & 6 \\
\end{pmatrix} \times \begin{pmatrix} 14 \\ 1 \end{pmatrix} =  \begin{pmatrix} 155 \\ 48 \end{pmatrix} \mod 26 = \begin{pmatrix} 25 \\ 22 \end{pmatrix} = \begin{pmatrix} Z \\ W \end{pmatrix} 
\end{equation}$$

$$\begin{equation}
\begin{pmatrix}
11 & 1 \\
3 & 6 \\
\end{pmatrix} \times \begin{pmatrix} 0 \\ 13 \end{pmatrix} =  \begin{pmatrix} 13 \\ 78 \end{pmatrix} \mod 26 = \begin{pmatrix} 13 \\ 0 \end{pmatrix} = \begin{pmatrix} N \\ A \end{pmatrix} 
\end{equation}$$

$$\begin{equation}
\begin{pmatrix}
11 & 1 \\
3 & 6 \\
\end{pmatrix} \times \begin{pmatrix} 20 \\ 23 \end{pmatrix} =  \begin{pmatrix} 243 \\ 198 \end{pmatrix} \mod 26 = \begin{pmatrix} 9 \\ 16 \end{pmatrix} = \begin{pmatrix} J \\ Q \end{pmatrix} 
\end{equation}$$

Text criptat rezultat: __ECZWNAJQ__

Decriptarea:

Daca matricea __Key__ este inversabila, atunci exista Key^-1 care se poate calcula folosind formula:
$$\begin{pmatrix} a & b \\ c & d \end{pmatrix}^{-1}=(ad-bc)^{-1}\begin{pmatrix} d & -b \\ -c & a \end{pmatrix}$$

$$\begin{equation}
Key^{-1}\mod 26 = 
\begin{pmatrix}
10 & 7 \\
21 & 1 \\
\end{pmatrix}
\end{equation}$$

Apoi se inmultesc matricile de 2 elemente rezultate din criptare, cu inversa matricei __K__ modulo 26 pentru a afla textul initial.

$$\begin{equation}
\begin{pmatrix}
10 & 7 \\
21 & 1 \\
\end{pmatrix} \times \begin{pmatrix} 4 \\ 2 \end{pmatrix} =  \begin{pmatrix} 54 \\ 86 \end{pmatrix} \mod 26 = \begin{pmatrix} 2 \\ 8 \end{pmatrix} =  \begin{pmatrix} C \\ I \end{pmatrix} 
\end{equation}$$

$$\begin{equation}
\begin{pmatrix}
10 & 7 \\
21 & 1 \\
\end{pmatrix} \times \begin{pmatrix} 25 \\ 22 \end{pmatrix} =  \begin{pmatrix} 404 \\ 547 \end{pmatrix} \mod 26 = \begin{pmatrix} 14 \\ 1 \end{pmatrix} = \begin{pmatrix} O \\ B \end{pmatrix} 
\end{equation}$$

$$\begin{equation}
\begin{pmatrix}
10 & 7 \\
21 & 1 \\
\end{pmatrix} \times \begin{pmatrix} 13 \\ 0 \end{pmatrix} =  \begin{pmatrix} 130 \\ 273 \end{pmatrix} \mod 26 = \begin{pmatrix} 0 \\ 13 \end{pmatrix} = \begin{pmatrix} A \\ N \end{pmatrix} 
\end{equation}$$

$$\begin{equation}
\begin{pmatrix}
10 & 7 \\
21 & 1 \\
\end{pmatrix} \times \begin{pmatrix} 9 \\ 16 \end{pmatrix} =  \begin{pmatrix} 202 \\ 205 \end{pmatrix} \mod 26 = \begin{pmatrix} 20 \\ 23 \end{pmatrix} = \begin{pmatrix} U \\ X \end{pmatrix} 
\end{equation}$$

In [3]:
import numpy as np
from numpy.linalg import inv
import string

#Generarea alfabetului
alphabet =  list(string.ascii_lowercase)
#alphalen = range(len(alphabet))

#Textul ce urmeaza a fi criptat
text = ['ci','ob','an','ux']

key = np.matrix([[11,1],[3,6]])
digram = []
for item in text:
        if item[0] in alphabet or item[1] in alphabet:
                digram.append(alphabet.index(item[0])), digram.append(alphabet.index(item[1]))
#Lista de digrams
digram = [np.matrix(digram[i:i+2]).reshape((2, 1)) for i  in range(0, len(digram), 2)]

criptare = []
for item in digram:
        criptare.append((key * item) % 26)

print(criptare)

keydet = np.linalg.det(key) % 26
# inv , d*d^-1 = 1 mod 26 , 11 * x = 1 mod 26 => x=19
inv = (19 * np.matrix([[6,-1],[-3,11]])) % 26

for item in criptare:
        print((inv * item) % 26)


[matrix([[4],
        [2]]), matrix([[25],
        [22]]), matrix([[13],
        [ 0]]), matrix([[ 9],
        [16]])]
[[2]
 [8]]
[[14]
 [ 1]]
[[ 0]
 [13]]
[[20]
 [23]]


__1.5 Să se cifreze textul reprezentat de numele dumneavoastră de familie, prin metoda transpoziţiei. Cheia utilizată în generarea permutării este data de numele şi prenumele dumneavoastră. Verificaţi rezultatul prin descifrare.__

Text de cifrat: __CIOBANU__

Cheie initiala: COSMINCIOBANU

Cheie adaptata: __COSMINC__ 

Nota: In cazul in care dimensiunea cheii de cifrare este mai mare decat dimensiunea textului ce urmeaza a fi cifrat , dimensiunea cheii de cifrare se egaleaza cu dimensiunea textului.


Cheie | C | O | S | M | I | N | C
---|---|---|---|---|---|---|---
Ord.col | 0 | 5 | 6 | 3 | 2 | 4 | 1
   Text | C | I | O | B | A | N | U
  Cifrare| C | N | U | B | O | A | I  




In [3]:
key = ['c','o','s','m','i','n','c']
key_index = [0,5,6,3,2,4,1]
text = ['c','i','o','b','a','n','u']
sorted_key = sorted(key)
encrypted = [text[i] for i in key_index]
print('Text criptat:',encrypted)

Text criptat: ['c', 'n', 'u', 'b', 'o', 'a', 'i']


__1.6 Să se cifreze textul reprezentat de prenumele dumeavoastră, cu ajutorul algoritmului Vigenere. Cheia utilizată este  data de numele dumneavoastră de familie. Verificaţi rezultatul prin descifrare.__

Text de cifrat: COSMIN (M)

Cheie: CIOBANU (K) 

Criptare:

$$C_i = E_K(M_i) = (M_i+K_i) \mod {26}$$

Decriptare:

$$M_i = D_K(C_i) = (C_i-K_i) \mod {26}$$

Exemplu:

Codul ASCII | 65 | 66 | 67 | 68 | 69 | 70 | 71 | 72 | 73 | 74 | 75 | 76 | 77 | 78 | 79 | 80 | 81 | 82 | 83 | 84 | 85 | 86 | 87 | 88 | 89 | 90
---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
Caracter | A | B | C | D | E | F | G | H | I | J | K | L | M | N | O | P | Q | R | S | T | U | V | W | X | Y | Z

Sa luam ca exemplu primul caracter al textului ce urmeaza sa fie criptat impreuna cu primul caracter al cheii de criptare:

$$C_1 = E_K(M_1) = (M_1 + K_1) \mod {26} = (67 + 67) \mod {26} + 65 = 69 = E $$

$$C_2 = E_K(M_2) = (M_2 + K_2) \mod {26} = (79 + 73) \mod {26} + 65 = 87 = W $$

In [8]:
from itertools import starmap, cycle

def encrypt(message, key):
    def enc(c,k): return chr(((ord(k) + ord(c)) % 26) + ord('A'))
    return "".join(starmap(enc, zip(message, cycle(key))))

def decrypt(message, key):
    def dec(c,k): return chr(((ord(c) - ord(k)) % 26) + ord('A'))
    return "".join(starmap(dec, zip(message, cycle(key))))


text = "COSMIN"
key = "CIOBANU"

enc = encrypt(text,key)
dec = decrypt(enc,key)
print("Cripate",enc,"\nDecriptare",dec)

Cripate EWGNIA 
Decriptare COSMIN


__1.7 Prenumele dumneavoastră se converteşte în format ASCII şi devine intrare în algoritmul RIJNDAEL 128/128. Numele de familie se va converti similar numai că devine intrare în algoritmul de generare a subcheilor de rundă. Care este ieşirea din rutinele: SubBytes, ShiftRows, MixColumn si AddRoundKey, la iteraţia 5?__


Algoritmul AES lucreaza cu blocuri de 128 biti si chei de cifrare de 128, 192 respectiv 256 biti.
Conform specificatiilor algoritmului, AES-128 are 10 cicluri de repetitie a rutinelor de runda (__SubBytes, ShiftRows, MixColumn si AddRoundKey__).

Text clar: COSMIN == ASCII("COSMIN") == HEX("67 79 83 77 73 78") == 43 4f 53 4d 49 4e + padding pana la 128 de biti

Cheie de cifrare: CIOBANU == 67 73 79 66 65 78 85

Avand in vedere ca AES lucreaza cu chei de cifrare de dimensiune fixa de 128 de biti , cheia de mai sus trebuie dimensionata corespunzator astfel am repetat cuvantul dat pentru a intruni cerintele algoritmului si anume 16 bytes "__CIOBANUCIOBANUCI__"



$$INPUT = \begin{bmatrix}
43 & 4f & 53 & 4d \\
49 & 4e & 00 & 00 \\
00 & 00 & 00 & 00 \\
00 & 00 & 00 & 00 \\
\end{bmatrix}$$

$$Cheie = \begin{bmatrix}
43 & 49 & 4f & 42\\ 
41 & 4e & 55 & 43\\
49 & 4f & 42 & 41\\ 
4e & 55 & 43 & 49\\
\end{bmatrix}$$

Descrierea etapelor:

1. __KeyExpansions__: In aceasta etapa cheia initiala de 128 biti este expandata in numarul de runde/cicluri + 1 chei, in cazul nostru 11 alte chei.
2. __InitialRound__: Fiecare byte din matricea de stare se combina folosind operatia de xor cu fiecare byte din sub cheia de runda.

$$\begin{bmatrix}
a_0 & a_4 & a_8 & a_{12} \\
a_1 & a_5 & a_9 & a_{13} \\
a_2 & a_6 & a_{10} & b_{14} \\
a_3 & a_7 & a_{11} & a_{15}
\end{bmatrix} \mathbin{\oplus} \begin{bmatrix}
k_0 & k_4 & k_8 & k_{12} \\
k_1 & k_5 & k_9 & k_{13} \\
k_2 & k_6 & k_{10} & k_{14} \\
k_3 & k_7 & k_{11} & k_{15}
\end{bmatrix} = 
\begin{bmatrix} 
b_0 & b_4 & b_8 & b_{12} \\
b_1 & b_5 & b_9 & b_{13} \\
b_2 & b_6 & b_{10} & b_{14} \\
b_3 & b_7 & b_{11} & b_{15}
\end{bmatrix}$$

3. Rounds (Runde):

    __SubBytes__— la aceasta etapa are loc o substitutie non-liniara unde fiecare byte este inlocuit cu un corespondent dintr-o table pre-definita __S-Box__. S-box este generat prin determinarea inversului multiplicativ al unui numar dat,  in GF(2^8) = GF(2)[x]/(x8 + x4 + x3 + x + 1).
    
Row  | 0  |  1 |  2 |  3 |  4 |  5 |  6 |  7 |  8 |  9 |  a |  b |  c |  d |  e | f
 --- |---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|--- 
00  | 52 | 09 | 6a | d5 | 30 | 36 | a5 | 38 | bf | 40 | a3 | 9e | 81 | f3 | d7 | fb  
10  | 7c | e3 | 39 | 82 | 9b | 2f | ff | 87 | 34 | 8e | 43 | 44 | c4 | de | e9 | cb  
20  | 54 | 7b | 94 | 32 | a6 | c2 | 23 | 3d | ee | 4c | 95 | 0b | 42 | fa | c3 | 4e  
30  | 08 | 2e | a1 | 66 | 28 | d9 | 24 | b2 | 76 | 5b | a2 | 49 | 6d | 8b | d1 | 25  
40  | 72 | f8 | f6 | 64 | 86 | 68 | 98 | 16 | d4 | a4 | 5c | cc | 5d | 65 | b6 | 92  
50  | 6c | 70 | 48 | 50 | fd | ed | b9 | da | 5e | 15 | 46 | 57 | a7 | 8d | 9d | 84  
60  | 90 | d8 | ab | 00 | 8c | bc | d3 | 0a | f7 | e4 | 58 | 05 | b8 | b3 | 45 | 06  
70  | d0 | 2c | 1e | 8f | ca | 3f | 0f | 02 | c1 | af | bd | 03 | 01 | 13 | 8a | 6b  
80  | 3a | 91 | 11 | 41 | 4f | 67 | dc | ea | 97 | f2 | cf | ce | f0 | b4 | e6 | 73  
90  | 96 | ac | 74 | 22 | e7 | ad | 35 | 85 | e2 | f9 | 37 | e8 | 1c | 75 | df | 6e  
a0  | 47 | f1 | 1a | 71 | 1d | 29 | c5 | 89 | 6f | b7 | 62 | 0e | aa | 18 | be | 1b  
b0  | fc | 56 | 3e | 4b | c6 | d2 | 79 | 20 | 9a | db | c0 | fe | 78 | cd | 5a | f4  
c0  | 1f | dd | a8 | 33 | 88 | 07 | c7 | 31 | b1 | 12 | 10 | 59 | 27 | 80 | ec | 5f  
d0  | 60 | 51 | 7f | a9 | 19 | b5 | 4a | 0d | 2d | e5 | 7a | 9f | 93 | c9 | 9c | ef  
e0  | a0 | e0 | 3b | 4d | ae | 2a | f5 | b0 | c8 | eb | bb | 3c | 83 | 53 | 99 | 61  
f0  | 17 | 2b | 04 | 7e | ba | 77 | d6 | 26 | e1 | 69 | 14 | 63 | 55 | 21 | 0c | 7d   


  __ShiftRows__— aici are loc o transpozitie unde ultimele 3 randuri ale matricei de stare sunt deplasate ciclic un anumit numar de pasi.
  
  __MixColumns__— operatie aplicata pe coloanele matricei de stare ce combina cei 4 bytes din fiecare coloana.
  
  __AddRoundKey__- la aceasta etapa se aplica operatia xor cu cheia de runda corespunzatoare

4. Runda finala:

    In ultima runda au loc doar 3 operatii:
    
    __SubBytes__.

    __ShiftRows__.
    
    __AddRoundKey__.

Folosind implementarea AES in JavaScript aflata aici (http://people.eku.edu/styere/Encrypt/JS-AES.html), am modificat codul astfel incat sa pot folosii cheia privata mentionata mai sus.